spring:
    # autoconfigure:
    #     exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
    datasource:
        url: jdbc:postgresql://localhost:5332/food_delivery
        username: rachidj
        password: rachidj
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format-size: true
        show-sql: true
    main:
        web-application-type: servlet
    security:
        user:
            password: qwerty